#Shape and ndim

In [7]:

import numpy as np
a=np.array([[1,2,3,4,5,6],[1,2,3,5,5,6]])
print(f"The dimention of this matrix is {a.ndim}")
print(f"The shape of this matrix is {a.shape}")

The dimention of this matrix is 2
The shape of this matrix is (2, 6)


In [6]:
a=np.array([[
    [1,2,3,4],
[1,2,3,4]
],[[1,2,3,4],[1,2,3,4]],])
print(f"The dimention of this matrix is {a.ndim}")
print(f"The shape of this matrix is {a.shape}")

The dimention of this matrix is 3
The shape of this matrix is (2, 2, 4)


In [4]:
b=np.array([1,2,3,4,5,6,7,8,9])
c=b.reshape(3,3)
print(c)
print(b.shape)
print(c.shape)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
(9,)
(3, 3)


In [8]:
arr = np.array([1,2,3,4])
arr = arr**2
print(arr)

[ 1  4  9 16]


In [ ]:
arr= np.array([10,20,30,40])
arr= arr>25  #Boolean
print(arr)

[False False  True  True]


In [19]:
#Write a program calaculated add, sunstract, mul, div and sqr of ann array in numpy.
#also find the data of each variable taking its mean value. Show data greater than mean value.

import numpy as np

# array
arr = np.array([20, 30, 40, 50])

# operations
a1 = arr + 5
b1 = arr - 10
c1 = arr * 5
d1 = arr / 5
e1 = arr ** 2

# mean
mean = np.mean(arr)

# values greater than mean
greater = arr > mean

print("Add:", a1)
print("Subtract:", b1)
print("Multiply:", c1)
print("Divide:", d1)
print("Square:", e1)
print("Mean:", mean)
print("Greater than mean (True/False):", greater)
print("Values greater than mean:", arr[arr > mean])



Add: [25 35 45 55]
Subtract: [10 20 30 40]
Multiply: [100 150 200 250]
Divide: [ 4.  6.  8. 10.]
Square: [ 400  900 1600 2500]
Mean: 35.0
Greater than mean (True/False): [False False  True  True]
Values greater than mean: [40 50]


In [20]:
#Mathmetic Function
np.sqrt(arr)
np.log(arr)
np.sin(arr)
np.cos(arr)
np.tan(arr)
np.sum(arr)

np.int64(140)

In [22]:

arr = [0, np.pi/2, np.pi/3, np.pi]
s1 = np.sin(arr)
np.cos(arr)
print("Sine values:", s1)
print(arr)


Sine values: [0.00000000e+00 1.00000000e+00 8.66025404e-01 1.22464680e-16]
[0, 1.5707963267948966, 1.0471975511965976, 3.141592653589793]


In [23]:
arr = [1, 3, 5, 256]
print(np.log(arr))

[0.         1.09861229 1.60943791 5.54517744]


In [29]:
# a= np.array([[1,2,3],[2,3,4]])
a= np.array([2,3,4,5,6,7])
# np.sum(arr)
np.mean(arr)
np.std(arr)
np.median(arr)

np.float64(4.0)

In [35]:
a= np.array([[1,2,3],
             [2,3,4]])
#np.sum(a, axis=0) #column wise sum
np.sum(a, axis=1) #row wise sum

array([6, 9])

In [38]:
# Find mean, median, mode, standard deviation, variance, min, max of an array
a = np.array([10,11,12,13,14])
mean= np.mean(a)
median= np.median(a)
# mode = np.
std = np.std(a)
var = np.var(a)
min = np.min(a)
max = np.max(a)
print("mean:",mean)
print("median:",median)
print("standard deviation:",std)
print("variance:",var)
print("min:",min)
print("max:",max)


mean: 12.0
median: 12.0
standard deviation: 1.4142135623730951
variance: 2.0
min: 10
max: 14


In [52]:
arr = np.array([200,400,500,600,700])
brr= np.array([56,74,16,96,18])

np.percentile(arr,10)
np.quantile(arr,0.15)
# np.corrcoef(arr,brr) #correlation

np.float64(320.0)

#---------------------------------------------Numpy Assignment-----------------------------------------

<!-- statistics,mean, median, standard deviations  sab kuch padh k aayek -->

# Section A: Data Types

In [4]:
# Create arrays with:
# •	int32 
# •	float64 
# •	bool 
# •	datetime64 

import numpy as np

# int32 array
arr_int = np.array([1, 2, 3, 4], dtype=np.int32)

# float64 array
arr_float = np.array([1.5, 2.5, 3.5], dtype=np.float64)

# bool array
arr_bool = np.array([True, False, True], dtype=bool)

# datetime64 array
arr_date = np.array(['2025-01-01', '2025-05-06'], dtype='datetime64')

# Display arrays
print("int32 array:", arr_int)
print("float64 array:", arr_float)
print("bool array:", arr_bool)
print("datetime64 array:", arr_date)

int32 array: [1 2 3 4]
float64 array: [1.5 2.5 3.5]
bool array: [ True False  True]
datetime64 array: ['2025-01-01' '2025-05-06']


In [6]:
# Convert:
# [1, 2, 3, 4]
# to float64.

arr = np.array([1, 2, 3, 4], dtype=np.float64)

print(arr)
print(arr.dtype)


[1. 2. 3. 4.]
float64


In [7]:
# Check dtype of:
# np.array([1.5, 2.5, 3.5])

arr = np.array([1.5, 2.5, 3.5])

print(arr.dtype)

float64


In [ ]:
# Create an array of dates for 7 days.

# create 7 consecutive dates starting from today
import numpy as np
dates = np.arange('2025-05-01', '2025-05-08', dtype='datetime64[D]')

print(dates)

['2025-05-01' '2025-05-02' '2025-05-03' '2025-05-04' '2025-05-05'
 '2025-05-06' '2025-05-07']


Why is dtype important in NumPy?
Ans: dtype (data type) tells NumPy what kind of data is stored in an array. It is very important for several reasons:
1.Memory Efficiency
2.Performance (Speed)
3.Accuracy & Precision
4.Type Safety
5.Operation Behavior

# Section B: Vectorization

In [10]:
# Add 13% tax to:
# prices = [100, 200, 300, 400]
import numpy as np

prices = np.array([100, 200, 300, 400])

# add 13% tax
final_prices = prices * 1.13

print(final_prices)

[113. 226. 339. 452.]


In [11]:
# increase salaries by 10%.
import numpy as np

salaries = np.array([1000, 2000, 3000, 4000])

# increase by 10%
new_salaries = salaries * 1.10

print(new_salaries)

[1100. 2200. 3300. 4400.]


In [12]:
# Convert Celsius to Fahrenheit.
# Formula:
# F = (C * 9/5) + 32
import numpy as np

celsius = np.array([0, 20, 30, 40])

fahrenheit = (celsius * 9/5) + 32

print(fahrenheit)


[ 32.  68.  86. 104.]


In [13]:
# Apply 20% discount.
import numpy as np

prices = np.array([100, 200, 300, 400])

# apply 20% discount
discounted_prices = prices * 0.80

print(discounted_prices)

[ 80. 160. 240. 320.]


In [ ]:
# Calculate bonus:
# •	salary > 50000 → 15% 
# •	else 5% 
import numpy as np

salaries = np.array([30000, 50000, 60000, 80000])

# apply condition
bonus = np.where(salaries > 50000, salaries * 0.15, salaries * 0.05)

print(bonus)


[ 1500.  2500.  9000. 12000.]


# Section C: Broadcasting

In [1]:
# Add scalar 10 to matrix.
import numpy as np

matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])

# add scalar 10
result = matrix + 10

print(result)

[[11 12 13]
 [14 15 16]]


In [ ]:
# Add vector: [10, 20, 30]
# to matrix rows.

matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])

vector = np.array([10, 20, 30])

# add vector to matrix rows
result = matrix + vector

print(result)


[[11 22 33]
 [14 25 36]]


In [7]:
# Multiply column vector with matrix

matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])

# column vector
col_vector = np.array([[10],
                       [20]])

# multiply column vector with matrix
result = matrix * col_vector

print(result)

[[ 10  20  30]
 [ 80 100 120]]


In [8]:
# Broadcast row vector.
import numpy as np

matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])

# row vector
row_vector = np.array([10, 20, 30])

# broadcasting row vector
result = matrix + row_vector

print(result)

[[11 22 33]
 [14 25 36]]


# Explain broadcasting rules.
1. NumPy Broadcasting Rules
Ans: Broadcasting is a NumPy feature that allows arrays of different shapes to perform operations together automatically.
Broadcasting Rules :-

Rule 1: Same Shape
    import numpy as np
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])
Output:
[11 22 33]

print(a + b)

Rule 2: One Dimension is 1
    If one dimension is 1, NumPy stretches it automatically.
import numpy as npa = np.array([[1], [2], [3]])b = np.array([10, 20, 30])print(a + b)
Output
[[11 21 31] [12 22 32] [13 23 33]]

Rule 3: Scalar Broadcasting

    A single number (scalar) is applied to all elements.

import numpy as np

a = np.array([1, 2, 3])

print(a + 5)
Output
[6 7 8]

Rule 4: Incompatible Shapes → Error
    import numpy as npa = np.array([1, 2, 3])b = np.array([1, 2])print(a + b)
❌ Error
ValueError: operands could not be broadcast together
Because:


shape (3,)


shape (2,)


These are not compatible.

📊 Shape Comparison Example
Array A ShapeArray B ShapeResult(3,3)(3,3)✅ Works(3,3)(3,)✅ Works(3,3)(1,3)✅ Works(3,3)(3,1)✅ Works(3,3)(2,3)❌ Error




# Section D: Mathematical Functions

In [9]:
# Dataset:
# sales = np.array([120, 140, 200, 250, 300])
import numpy as np

# dataset
sales = np.array([120, 140, 200, 250, 300])

print(sales)

[120 140 200 250 300]


In [ ]:
# Calculate: •	sum,  •	mean,  •	median 

total = np.sum(sales)
mean = np.mean(sales)
median = np.median(sales)

print("Sum:", total)
print("Mean:", mean)
print("Median:", median)


Sum: 1010
Mean: 202.0
Median: 200.0


In [ ]:
# Calculate: •	std ,  •	variance 

std = np.std(sales)
variance = np.var(sales)

print("Standard Deviation:", std)
print("Variance:", variance)


In [12]:
# Find: •	min ,  •	max 

minimum = np.min(sales)
maximum = np.max(sales)

print("Minimum:", minimum)
print("Maximum:", maximum)


Minimum: 120
Maximum: 300


In [14]:
numbers = np.array([4, 9, 16, 25, 36])

# calculate square root
result = np.sqrt(numbers)

print(result)

[2. 3. 4. 5. 6.]


In [15]:
# Calculate log values.
result= np.log(numbers)
print(result)

[1.38629436 2.19722458 2.77258872 3.21887582 3.58351894]


In [16]:

numbers = np.array([1, 10, 100, 1000])

# natural log (base e)
ln_values = np.log(numbers)

# log base 10
log10_values = np.log10(numbers)

# log base 2
log2_values = np.log2(numbers)

print("Natural log:", ln_values)
print("Log10:", log10_values)
print("Log2:", log2_values)

Natural log: [0.         2.30258509 4.60517019 6.90775528]
Log10: [0. 1. 2. 3.]
Log2: [0.         3.32192809 6.64385619 9.96578428]


In [20]:
# Calculate cumulative sum.

sales = np.array([120, 140, 200, 250, 300])
# cumulative sum
cumsum = np.cumsum(sales)

print(cumsum)

[ 120  260  460  710 1010]


# Section E: Axis