#Shape and ndim

In [7]:

import numpy as np
a=np.array([[1,2,3,4,5,6],[1,2,3,5,5,6]])
print(f"The dimention of this matrix is {a.ndim}")
print(f"The shape of this matrix is {a.shape}")

The dimention of this matrix is 2
The shape of this matrix is (2, 6)


In [6]:
a=np.array([[
    [1,2,3,4],
[1,2,3,4]
],[[1,2,3,4],[1,2,3,4]],])
print(f"The dimention of this matrix is {a.ndim}")
print(f"The shape of this matrix is {a.shape}")

The dimention of this matrix is 3
The shape of this matrix is (2, 2, 4)


In [4]:
b=np.array([1,2,3,4,5,6,7,8,9])
c=b.reshape(3,3)
print(c)
print(b.shape)
print(c.shape)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
(9,)
(3, 3)


In [8]:
arr = np.array([1,2,3,4])
arr = arr**2
print(arr)

[ 1  4  9 16]


In [ ]:
arr= np.array([10,20,30,40])
arr= arr>25  #Boolean
print(arr)

[False False  True  True]


In [19]:
#Write a program calaculated add, sunstract, mul, div and sqr of ann array in numpy.
#also find the data of each variable taking its mean value. Show data greater than mean value.

import numpy as np

# array
arr = np.array([20, 30, 40, 50])

# operations
a1 = arr + 5
b1 = arr - 10
c1 = arr * 5
d1 = arr / 5
e1 = arr ** 2

# mean
mean = np.mean(arr)

# values greater than mean
greater = arr > mean

print("Add:", a1)
print("Subtract:", b1)
print("Multiply:", c1)
print("Divide:", d1)
print("Square:", e1)
print("Mean:", mean)
print("Greater than mean (True/False):", greater)
print("Values greater than mean:", arr[arr > mean])



Add: [25 35 45 55]
Subtract: [10 20 30 40]
Multiply: [100 150 200 250]
Divide: [ 4.  6.  8. 10.]
Square: [ 400  900 1600 2500]
Mean: 35.0
Greater than mean (True/False): [False False  True  True]
Values greater than mean: [40 50]


In [20]:
#Mathmetic Function
np.sqrt(arr)
np.log(arr)
np.sin(arr)
np.cos(arr)
np.tan(arr)
np.sum(arr)

np.int64(140)

In [22]:

arr = [0, np.pi/2, np.pi/3, np.pi]
s1 = np.sin(arr)
np.cos(arr)
print("Sine values:", s1)
print(arr)


Sine values: [0.00000000e+00 1.00000000e+00 8.66025404e-01 1.22464680e-16]
[0, 1.5707963267948966, 1.0471975511965976, 3.141592653589793]


In [23]:
arr = [1, 3, 5, 256]
print(np.log(arr))

[0.         1.09861229 1.60943791 5.54517744]


In [29]:
# a= np.array([[1,2,3],[2,3,4]])
a= np.array([2,3,4,5,6,7])
# np.sum(arr)
np.mean(arr)
np.std(arr)
np.median(arr)

np.float64(4.0)

In [35]:
a= np.array([[1,2,3],
             [2,3,4]])
#np.sum(a, axis=0) #column wise sum
np.sum(a, axis=1) #row wise sum

array([6, 9])

In [38]:
# Find mean, median, mode, standard deviation, variance, min, max of an array
a = np.array([10,11,12,13,14])
mean= np.mean(a)
median= np.median(a)
# mode = np.
std = np.std(a)
var = np.var(a)
min = np.min(a)
max = np.max(a)
print("mean:",mean)
print("median:",median)
print("standard deviation:",std)
print("variance:",var)
print("min:",min)
print("max:",max)


mean: 12.0
median: 12.0
standard deviation: 1.4142135623730951
variance: 2.0
min: 10
max: 14


In [52]:
arr = np.array([200,400,500,600,700])
brr= np.array([56,74,16,96,18])

np.percentile(arr,10)
np.quantile(arr,0.15)
# np.corrcoef(arr,brr) #correlation

np.float64(320.0)