In [1]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [2]:
print(type(arr))

<class 'numpy.ndarray'>


In [3]:
x= np.array(34)
print(x)

34


In [ ]:
print(type(x))  #Zero dimension array

<class 'numpy.ndarray'>


In [22]:
arr = np.array([1,2,3,4],ndmin=4)

print(arr)
print('Number of dimension:',arr.ndim)


[[[[1 2 3 4]]]]
Number of dimension: 4


In [23]:
print(arr[0])

[[[1 2 3 4]]]


#Slicing

In [25]:
arr = np.array([1,2,3,4,5,6,7,8])
x= arr[1:6]
print("The number find:", x)
x1 = arr[2:4:6]
print(x1)


The number find: [2 3 4 5 6]
[3]


In [ ]:
# i = integer(1,2,3)
# b = Bollean (T, F)
# u = unsigined int (0 to positive)
# f = float (1.5, 2.7)
# c = complex (1+2j)
# m = Timedelta (5 days)
# M = Date time (2025-12-21)
# O = Object (mixed data)
# S = Byte string  (b"hello")
# U = Unicode string (Hello)
# V = void (raw Memory)

In [8]:
import numpy as np

# a = np.array([1,2,3,4], dtype="i8")
a = np.array(["2025-12-31"],dtype="M")
b= np.array(["Sachendra","Nawaraj","Balkrishna"])
c= np.array
print(a.dtype)
print(b.dtype)


datetime64[D]
<U10


In [ ]:
import numpy as np

a1= np.array([1,2,3,4,5], dtype="i")
b1= np.array(["True","False"], dtype=bool)
# c1 =np.array([-3,-2,-1,0,1,2,3], dtype="u")
d1 =np.array([1.2,2.3,34.4], dtype="f")
e1 =np.array(["1+2j","1-3i"], dtype="c")
f1 =np.array(["2021-12-31"],dtype="M")
g1 =np.array(["1,2,3,4,5"],dtype="O")
h1 =np.array(["bkc", "csk","skc"],dtype="S")
i1 =np.array(["bkc", "csk","skc","psk"],dtype="U")
# j1 =np.array(["bkc", "csk","skc","psk"],dtype="V")


print(a1.dtype)
print(b1.dtype)
# print(c1.dtype)
print(d1.dtype)
print(e1.dtype)
print(f1.dtype)
print(g1.dtype)
print(h1.dtype)
print(i1.dtype)
# print(j1.dtype)





int32
bool
float32
|S1
datetime64[D]
object
|S3
<U3


In [6]:
import numpy as np

# i → integer
a1 = np.array([1, 2, 3, 4, 5], dtype="i")

# b → boolean
b1 = np.array([True, False, True], dtype="b")

# u → unsigned integer
# u1 = np.array([1, 2, 3, 4, 5], dtype="u")

# f → float
f1 = np.array([1.5, 2.7, 3.9], dtype="f")

# c → complex
c1 = np.array([1+2j, 2-3j], dtype="c")

# m → timedelta
m1 = np.array([np.timedelta64(5, 'D'), np.timedelta64(2, 'D')], dtype="m")

# M → datetime
M1 = np.array(["2025-12-21", "2026-01-01"], dtype="M")

# O → object
O1 = np.array([1, "hello", 3.5], dtype="O")

# S → byte string
S1 = np.array([b"hello", b"world"], dtype="S")

# U → unicode string
U1 = np.array(["Hello", "Nepal"], dtype="U")

# V → void (raw memory)
# V1 = np.array([(1, 2), (3, 4)], dtype="V")


# OUTPUT
print("i (int)        :", a1, "dtype:", a1.dtype)
print("b (bool)       :", b1, "dtype:", b1.dtype)
# print("u (unsigned)   :", u1, "dtype:", u1.dtype)
print("f (float)      :", f1, "dtype:", f1.dtype)
print("c (complex)    :", c1, "dtype:", c1.dtype)
print("m (timedelta)  :", m1, "dtype:", m1.dtype)
print("M (datetime)   :", M1, "dtype:", M1.dtype)
print("O (object)     :", O1, "dtype:", O1.dtype)
print("S (byte string):", S1, "dtype:", S1.dtype)
print("U (unicode)    :", U1, "dtype:", U1.dtype)
# print("V (void)       :", V1, "dtype:", V1.dtype)

i (int)        : [1 2 3 4 5] dtype: int32
b (bool)       : [1 0 1] dtype: int8
f (float)      : [1.5 2.7 3.9] dtype: float32
c (complex)    : [b'(' b'('] dtype: |S1
m (timedelta)  : [5 2] dtype: timedelta64[D]
M (datetime)   : ['2025-12-21' '2026-01-01'] dtype: datetime64[D]
O (object)     : [1 'hello' 3.5] dtype: object
S (byte string): [b'hello' b'world'] dtype: |S5
U (unicode)    : ['Hello' 'Nepal'] dtype: <U5
