In [ ]:
!pip install numpy

In [ ]:
import numpy as np
a1 = np.array([1,2,3])
print(a1)

[1 2 3]


In [2]:
b= np.zeros((2,3))
print(b)

[[0. 0. 0.]
 [0. 0. 0.]]


In [5]:
c=np.ones((3,3))
print(c)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [10]:
d = np.arange(0,12,2)
print(d)

[ 0  2  4  6  8 10]


In [11]:
e = np.linspace(0,1,5)
print(e)

[0.   0.25 0.5  0.75 1.  ]


In [13]:
import numpy as np

a= np.array([9,10,15,20,30])
print(a[0])
print(a[4])
print(a[2])

9
30
15


In [17]:
import numpy as np

a= np.array([100,200,300,400])
print(a[-1])
print(a[-2])
print(a[-4])

400
300
100


In [23]:
import numpy as np

b= np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(b[1,1])
print(b[2,2])
print(b[0,1])

5
9
2


In [33]:
import numpy as np

b= np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(b[0])   #print(b[:,0])
print(b[1])
print(b[2])

[1 2 3]
[4 5 6]
[7 8 9]


In [49]:
b = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120]
])
print(b[:2,(1,2)])
print("--------------------")
print(b[:3,3])
print("--------------------")
print(b[1:3,(1,2,3)])

[[20 30]
 [60 70]]
--------------------
[ 40  80 120]
--------------------
[[ 60  70  80]
 [100 110 120]]


In [66]:
b = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120]
])
print(b[0:2,1:3])
print("--------------------")
print(b[:,-1])
print("--------------------")
print(b[1:,1:])
print("--------------------")
print(b[0:2,2:])
print("--------------------")
print(b[0] + b[1])
print("--------------------")
print(b[0] * b[1])
print("--------------------")
print(b[1] / b[0])




[[20 30]
 [60 70]]
--------------------
[ 40  80 120]
--------------------
[[ 60  70  80]
 [100 110 120]]
--------------------
[[30 40]
 [70 80]]
--------------------
[ 60  80 100 120]
--------------------
[ 500 1200 2100 3200]
--------------------
[5.         3.         2.33333333 2.        ]


In [72]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)
print(a+10)
print(a*2)
print(a[::-1])  #reverse array a

[5 7 9]
[11 12 13]
[2 4 6]
[3 2 1]


In [1]:
c = np.array([
    [[1,2],[3,4]]
    [[5,6],[7,8]]
])
# print(c[1, 0, 1])
print(c.ndim)

<>:2: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:2: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
C:\Users\DELL\AppData\Local\Temp\ipykernel_5416\450938570.py:2: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  [[1,2],[3,4]]


NameError: name 'np' is not defined

In [2]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)
print(a+10)
print(a*2)
print(a[::-1])  #reverse array a

[5 7 9]
[11 12 13]
[2 4 6]
[3 2 1]


In [2]:
import numpy as np
print(np.__version__)

2.4.4
